### PR TITLE
Dev guide update

### PR DESCRIPTION
**Pull request by techfreaque**

### CODE REVIEW

**Comment by techfreaque** [comment]
I just improved this pull request again, please review and merge it as it helps new devs to get started easier

**Comment by Herklos** [comment]
Great job @techfreaque! We'll have a look at it soon

**Review by GuillaumeDSM — APPROVED** [review]
amazing job, thanks a lot !

**Review by Herklos — APPROVED** [review]
Thanks for your work @techfreaque !

**Pull request merged**
